version: '3'
services:
  node-app:
    image: node:18-alpine
    container_name: game-loop-processor
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: node process.js
    restart: always
